[tool.black]
line-length = 88
target-version = ["py312"]
extend-exclude = "migrations/"

[tool.isort]
profile = "black"
src_paths = ["app", "migrations"]
skip = ["__pycache__"]
line_length = 120
include_trailing_comma = true
multi_line_output = 3
combine_as_imports = true
known_first_party = ["app"]
skip_glob = ["migrations/versions/*"]

