"""add user_sessions, chat_reactions for respectively refresh tokens and add users reactions on the chat

Revision ID: 6b3a40b6ef38
Revises: 78e7cb60f430
Create Date: 2025-08-12 07:44:52.931155

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b3a40b6ef38"
down_revision: Union[str, Sequence[str], None] = "78e7cb60f430"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_reactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("emoji", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["chat_messages.id"],
            name=op.f("fk_chat_reactions_message_id_chat_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_chat_reactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_reactions")),
        sa.UniqueConstraint("message_id", "user_id", "emoji", name="uq_chat_reaction"),
    )
    op.create_index(
        op.f("ix_chat_reactions_message_id"),
        "chat_reactions",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_reactions_user_id"), "chat_reactions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_reactions_user_id"), table_name="chat_reactions")
    op.drop_index(op.f("ix_chat_reactions_message_id"), table_name="chat_reactions")
    op.drop_table("chat_reactions")
    # ### end Alembic commands ###
