"""initial schema v2

Revision ID: 78e7cb60f430
Revises:
Create Date: 2025-08-06 14:31:26.137084

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78e7cb60f430"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "theme", sa.Enum("LIGHT", "DARK", "AUTO", name="usertheme"), nullable=False
        ),
        sa.Column(
            "font_size",
            sa.Enum("SMALL", "MEDIUM", "LARGE", name="fontsize"),
            nullable=False,
        ),
        sa.Column("articles_per_page", sa.Integer(), nullable=False),
        sa.Column("auto_mark_read", sa.Boolean(), nullable=False),
        sa.Column("google_id", sa.String(length=100), nullable=True),
        sa.Column("github_id", sa.String(length=100), nullable=True),
        sa.Column("microsoft_id", sa.String(length=100), nullable=True),
        sa.Column("total_feeds", sa.Integer(), nullable=False),
        sa.Column("total_articles_read", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=False)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_microsoft_id"), "users", ["microsoft_id"], unique=False
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(length=100), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_personal", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("allow_comments", sa.Boolean(), nullable=False),
        sa.Column("allow_chat", sa.Boolean(), nullable=False),
        sa.Column("auto_fetch_feeds", sa.Boolean(), nullable=False),
        sa.Column("total_feeds", sa.Integer(), nullable=False),
        sa.Column("total_articles", sa.Integer(), nullable=False),
        sa.Column("total_members", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_activity",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_collections_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
    )
    op.create_index(op.f("ix_collections_id"), "collections", ["id"], unique=False)
    op.create_index(op.f("ix_collections_name"), "collections", ["name"], unique=False)
    op.create_index(
        op.f("ix_collections_owner_id"), "collections", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_collections_slug"), "collections", ["slug"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum(
                "TEXT",
                "SYSTEM",
                "ARTICLE_SHARE",
                "FEED_ADD",
                name="chat_message_type_enum",
            ),
            server_default="TEXT",
            nullable=False,
        ),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("is_edited", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("reply_to_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_chat_messages_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_chat_messages_collection_id_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["chat_messages.id"],
            name=op.f("fk_chat_messages_reply_to_id_chat_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(
        op.f("ix_chat_messages_author_id"), "chat_messages", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_messages_collection_id"),
        "chat_messages",
        ["collection_id"],
        unique=False,
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_chat_messages_reply_to_id"),
        "chat_messages",
        ["reply_to_id"],
        unique=False,
    )
    op.create_table(
        "collection_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("can_read", sa.Boolean(), nullable=False),
        sa.Column("can_add_feeds", sa.Boolean(), nullable=False),
        sa.Column("can_edit_feeds", sa.Boolean(), nullable=False),
        sa.Column("can_delete_feeds", sa.Boolean(), nullable=False),
        sa.Column("can_comment", sa.Boolean(), nullable=False),
        sa.Column("can_chat", sa.Boolean(), nullable=False),
        sa.Column("can_invite", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("invited_by", sa.Integer(), nullable=True),
        sa.Column("invitation_token", sa.String(length=100), nullable=True),
        sa.Column("invitation_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_activity",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_collection_members_collection_id_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_collection_members_invited_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_collection_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_members")),
    )
    op.create_index(
        op.f("ix_collection_members_collection_id"),
        "collection_members",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_members_id"), "collection_members", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_collection_members_invitation_token"),
        "collection_members",
        ["invitation_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_members_user_id"),
        "collection_members",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "feeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ERROR", "DELETED", name="feedstatus"),
            nullable=False,
        ),
        sa.Column("update_frequency", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("rss_title", sa.String(length=200), nullable=True),
        sa.Column("rss_description", sa.Text(), nullable=True),
        sa.Column("rss_image_url", sa.String(length=500), nullable=True),
        sa.Column("rss_generator", sa.String(length=100), nullable=True),
        sa.Column("rss_version", sa.String(length=10), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_modified", sa.String(length=100), nullable=True),
        sa.Column("etag", sa.String(length=100), nullable=True),
        sa.Column("last_build_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_articles", sa.Integer(), nullable=False),
        sa.Column("successful_fetches", sa.Integer(), nullable=False),
        sa.Column("failed_fetches", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_feeds_collection_id_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_feeds_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feeds")),
    )
    op.create_index(
        op.f("ix_feeds_collection_id"), "feeds", ["collection_id"], unique=False
    )
    op.create_index(op.f("ix_feeds_created_by"), "feeds", ["created_by"], unique=False)
    op.create_index(op.f("ix_feeds_id"), "feeds", ["id"], unique=False)
    op.create_index(op.f("ix_feeds_title"), "feeds", ["title"], unique=False)
    op.create_index(op.f("ix_feeds_url"), "feeds", ["url"], unique=False)
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column(
            "file_format",
            sa.Enum("OPML", "JSON", "CSV", name="fileformat"),
            nullable=False,
        ),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="importstatus",
            ),
            nullable=False,
        ),
        sa.Column("progress_percentage", sa.Integer(), nullable=False),
        sa.Column("total_feeds", sa.Integer(), nullable=False),
        sa.Column("imported_feeds", sa.Integer(), nullable=False),
        sa.Column("failed_feeds", sa.Integer(), nullable=False),
        sa.Column("skipped_feeds", sa.Integer(), nullable=False),
        sa.Column("success_message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.Column("target_collection_id", sa.Integer(), nullable=True),
        sa.Column("override_existing", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_collection_id"],
            ["collections.id"],
            name=op.f("fk_import_jobs_target_collection_id_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_import_jobs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
    )
    op.create_index(op.f("ix_import_jobs_id"), "import_jobs", ["id"], unique=False)
    op.create_index(
        op.f("ix_import_jobs_user_id"), "import_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("guid", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("reading_time", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("enclosure_url", sa.String(length=1000), nullable=True),
        sa.Column("enclosure_type", sa.String(length=50), nullable=True),
        sa.Column("enclosure_length", sa.Integer(), nullable=True),
        sa.Column("total_reads", sa.Integer(), nullable=False),
        sa.Column("total_favorites", sa.Integer(), nullable=False),
        sa.Column("total_comments", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["feed_id"], ["feeds.id"], name=op.f("fk_articles_feed_id_feeds")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
    )
    op.create_index(op.f("ix_articles_author"), "articles", ["author"], unique=False)
    op.create_index(op.f("ix_articles_feed_id"), "articles", ["feed_id"], unique=False)
    op.create_index(
        "ix_articles_feed_published",
        "articles",
        ["feed_id", "published_at"],
        unique=False,
    )
    op.create_index(op.f("ix_articles_guid"), "articles", ["guid"], unique=False)
    op.create_index(
        "ix_articles_guid_feed", "articles", ["guid", "feed_id"], unique=True
    )
    op.create_index(op.f("ix_articles_id"), "articles", ["id"], unique=False)
    op.create_index(
        op.f("ix_articles_published_at"), "articles", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_articles_title"), "articles", ["title"], unique=False)
    op.create_table(
        "feed_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_feed_categories_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"], ["feeds.id"], name=op.f("fk_feed_categories_feed_id_feeds")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feed_categories")),
    )
    op.create_index(
        op.f("ix_feed_categories_category_id"),
        "feed_categories",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feed_categories_feed_id"), "feed_categories", ["feed_id"], unique=False
    )
    op.create_index(
        op.f("ix_feed_categories_id"), "feed_categories", ["id"], unique=False
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("thread_level", sa.Integer(), nullable=False),
        sa.Column("is_edited", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("is_flagged", sa.Boolean(), nullable=False),
        sa.Column("upvotes", sa.Integer(), nullable=False),
        sa.Column("downvotes", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_comments_article_id_articles"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_comments_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["comments.id"], name=op.f("fk_comments_parent_id_comments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(
        op.f("ix_comments_article_id"), "comments", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False
    )
    op.create_index(op.f("ix_comments_id"), "comments", ["id"], unique=False)
    op.create_index(
        op.f("ix_comments_parent_id"), "comments", ["parent_id"], unique=False
    )
    op.create_table(
        "user_articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("favorited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_duration", sa.Integer(), nullable=True),
        sa.Column("user_notes", sa.Text(), nullable=True),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_user_articles_article_id_articles"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_articles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_articles")),
    )
    op.create_index(
        op.f("ix_user_articles_article_id"),
        "user_articles",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_articles_favorite",
        "user_articles",
        ["user_id", "is_favorite"],
        unique=False,
    )
    op.create_index(op.f("ix_user_articles_id"), "user_articles", ["id"], unique=False)
    op.create_index(
        "ix_user_articles_read", "user_articles", ["user_id", "is_read"], unique=False
    )
    op.create_index(
        "ix_user_articles_unique",
        "user_articles",
        ["user_id", "article_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_articles_user_id"), "user_articles", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_articles_user_id"), table_name="user_articles")
    op.drop_index("ix_user_articles_unique", table_name="user_articles")
    op.drop_index("ix_user_articles_read", table_name="user_articles")
    op.drop_index(op.f("ix_user_articles_id"), table_name="user_articles")
    op.drop_index("ix_user_articles_favorite", table_name="user_articles")
    op.drop_index(op.f("ix_user_articles_article_id"), table_name="user_articles")
    op.drop_table("user_articles")
    op.drop_index(op.f("ix_comments_parent_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_article_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_feed_categories_id"), table_name="feed_categories")
    op.drop_index(op.f("ix_feed_categories_feed_id"), table_name="feed_categories")
    op.drop_index(op.f("ix_feed_categories_category_id"), table_name="feed_categories")
    op.drop_table("feed_categories")
    op.drop_index(op.f("ix_articles_title"), table_name="articles")
    op.drop_index(op.f("ix_articles_published_at"), table_name="articles")
    op.drop_index(op.f("ix_articles_id"), table_name="articles")
    op.drop_index("ix_articles_guid_feed", table_name="articles")
    op.drop_index(op.f("ix_articles_guid"), table_name="articles")
    op.drop_index("ix_articles_feed_published", table_name="articles")
    op.drop_index(op.f("ix_articles_feed_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_author"), table_name="articles")
    op.drop_table("articles")
    op.drop_index(op.f("ix_import_jobs_user_id"), table_name="import_jobs")
    op.drop_index(op.f("ix_import_jobs_id"), table_name="import_jobs")
    op.drop_table("import_jobs")
    op.drop_index(op.f("ix_feeds_url"), table_name="feeds")
    op.drop_index(op.f("ix_feeds_title"), table_name="feeds")
    op.drop_index(op.f("ix_feeds_id"), table_name="feeds")
    op.drop_index(op.f("ix_feeds_created_by"), table_name="feeds")
    op.drop_index(op.f("ix_feeds_collection_id"), table_name="feeds")
    op.drop_table("feeds")
    op.drop_index(
        op.f("ix_collection_members_user_id"), table_name="collection_members"
    )
    op.drop_index(
        op.f("ix_collection_members_invitation_token"), table_name="collection_members"
    )
    op.drop_index(op.f("ix_collection_members_id"), table_name="collection_members")
    op.drop_index(
        op.f("ix_collection_members_collection_id"), table_name="collection_members"
    )
    op.drop_table("collection_members")
    op.drop_index(op.f("ix_chat_messages_reply_to_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_collection_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_author_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_collections_slug"), table_name="collections")
    op.drop_index(op.f("ix_collections_owner_id"), table_name="collections")
    op.drop_index(op.f("ix_collections_name"), table_name="collections")
    op.drop_index(op.f("ix_collections_id"), table_name="collections")
    op.drop_table("collections")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_microsoft_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
