"""add oauth_accounts

Revision ID: 8f07ed092cbf
Revises: 4a46ba3bf133
Create Date: 2025-09-01 03:34:03.491456

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f07ed092cbf'
down_revision: str | Sequence[str] | None = '4a46ba3bf133'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
