name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install \
            black==24.8.0 \
            isort==5.13.2 \
            flake8==7.1.1 \
            flake8-bugbear==24.4.26 \
            flake8-comprehensions==3.14.0 \
            mypy==1.10.0 \
            bandit==1.7.9 \
            pip-audit==2.7.3
          # dépendances du projet (adapter si tu utilises poetry)
          pip install -r backend/requirements.txt

      - name: Black (check)
        run: black --check backend

      - name: isort (check)
        run: isort --check-only backend

      - name: Flake8
        run: flake8 backend

      - name: Mypy (tolérant au début)
        continue-on-error: true
        run: mypy backend

      - name: Bandit (sécurité)
        run: bandit -q -r backend

      - name: pip-audit (vulnérabilités)
        continue-on-error: true
        run: pip-audit -r backend/requirements.txt

      - name: Smoke tests (facultatif si pas de tests encore)
        run: |
          pip install pytest
          pytest -q || true
