name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install auto-fix tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.5.5 autoflake==2.3.1 isort==5.13.2 black==24.8.0 pyupgrade==3.15.0
      - name: Auto-fix (ruff/autoflake/isort/black)
        run: |
          pyupgrade --py312-plus $(git ls-files '*.py')
          ruff --fix --unsafe-fixes backend
          autoflake -r -i --remove-all-unused-imports --remove-unused-variables --expand-star-imports backend
          isort backend
          black backend
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix (ruff/autoflake/isort/black) [skip ci]"

  quality:
    needs: autofix
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install \
            black==24.8.0 \
            isort==5.13.2 \
            flake8==7.1.1 \
            flake8-bugbear==24.4.26 \
            flake8-comprehensions==3.14.0 \
            mypy==1.10.0 \
            bandit==1.7.9 \
            pip-audit==2.7.3
          pip install -r backend/requirements.txt
      - name: Black (check)
        run: black --check backend
      - name: isort (check)
        run: isort --check-only backend
      - name: Flake8
        run: flake8 backend
      - name: Mypy (tolérant)
        continue-on-error: true
        run: mypy backend
      - name: Bandit
        run: bandit -q -r backend
      - name: pip-audit
        continue-on-error: true
        run: pip-audit -r backend/requirements.txt
